### ISSUE TITLE
About project idea

### ISSUE THREAD

**Issue by kanika-banga** [casbin/SummerOfCode2021#11]
Hello!
Greetings of the day.
I am kanika banga. I am a Computer Science student pursuing BCA 2nd year. I would like to contribute to your organization as I find it very well suitable for me. I wanted to ask if I can work on my own project. The project name is Palm Detection. It`s security related project. Technology used would be HTML, CSS & Javascript or Python. It is more secure than other biometrics because it is never exposed. This project would be best for the future as the technology would be enhanced using internal organ rather than outer ones. As palm has more surface area than fingers or iris , so , It provide us more accurate results than other biometrics. The biometric being scanned is from a real person only , so , It can`t be stolen or duplicated. As the palm recognition is internal, It offers you with privacy advantage as well. Palm vein scanner is resistant to dirt, dust, dryness , moisture , etc. So, It is very much reliable.
Please consider this project. It would be a great opportunity for me to be guided by you.
Thank you
Stay Safe

**Comment by hsluoyz** [comment]
Hi @kanika-banga sorry that we can only work on Casbin-related projects. If you'd like to work on your own project, why not just open-source it on GitHub and attract contributors, or apply for some security-specific funds in your school or in Internet. Thanks!

**Comment by kanika-banga** [comment]
Ok. Thank you.
