### ISSUE TITLE
Casbin students for GSoC 2021!

### ISSUE THREAD

**Issue by hsluoyz** [casbin/SummerOfCode2021#12]
Our GSoC 2021 students are announced by Google today. We have 9 students for GSoC this year. Congratulations to all of you!

Go: @closetool 
Casdoor + Casnode: @Kininaru 
Node.js + Python: @Zxilly 
.NET: @Sagilio 
C/C++: @EmperorYP7 
Lua: @rushitote 
Rust: @smrpn
Dart: @MrUnfunny
K8s + OpenStack: @ashish493

https://summerofcode.withgoogle.com/organizations/6541614404599808/

**Comment by MrUnfunny** [comment]
Hi @hsluoyz
Thanks for the opportunity. Looking forward to contributing and learning a lot from the community.

**Comment by keainye** [comment]
@hsluoyz Thanks for giving me chance to participate in Google Summer of Code! Looking forward to writing code these days!

**Comment by Zxilly** [comment]
@hsluoyz Thanks for the opportunity. Hope to keep contributing to community.

**Comment by EmperorYP7** [comment]
@hsluoyz Thank you so much to the entire Casbin team. Glad to be a part of the community and help Casbin in its growth. Looking forward to learning and giving back to the community through my contributions! Congratulations to all other participants.

**Comment by rushitote** [comment]
> Our GSoC 2021 students are announced by Google today. We have 9 students for GSoC this year. Congratulations to all of you!
> 
> Go: @closetool
> Casdoor + Casnode: @Kininaru
> Node.js + Python: @Zxilly
> .NET: @Sagilio
> C/C++: @EmperorYP7
> Lua: @rushitote
> Rust: @smrpn
> Dart: @MrUnfunny
> K8s + OpenStack: @ashish493
> 
> https://summerofcode.withgoogle.com/organizations/6541614404599808/

Thank you very much!

**Comment by sagilio** [comment]
@hsluoyz Thanks for the opportunity! Hope to help the community continue to enhance.

**Comment by 0xethsign** [comment]
@hsluoyz Thanks so much to the entire Casbin community. Hope to see more developers use and engage with Casbin. Looking forward to a great fruitful summer. Congrats to all the other participants.

**Comment by kilosonc** [comment]
@hsluoyz Thanks for the opportunity. Hope to keep contributing to community.

**Comment by hsluoyz** [comment]
@all , GSoC coding has began! Please enroll in the weekly report system: https://gsoc.casbin.org/

You will submit the first week report after 3 days.

**Comment by hsluoyz** [comment]
@KNawm @hackerchai mentors please also log into https://gsoc.casbin.org/ to activate the mentor profile.

**Comment by hsluoyz** [comment]
@MrUnfunny @smrpn @EmperorYP7 plz submit your weekly report (Week 0) at: https://gsoc.casbin.org/

Ideally, we should:

1. Submit the next weekly report for each Tuesday.
2. We encourage students to also write technical blogs for Casbin and put the links into weekly report.

**Comment by rahulchandra17** [comment]
Hey I want to contribute.. please guide
